name: Del√∂vning 1 - Minimal Pipeline

on:
  # ska startas manuellt
  workflow_dispatch:
jobs:
  echo-pipeline:
    runs-on: macos-latest
    steps:
      - name: Confirm pipeline has started
        run: echo "pipeline has started"
  echo-python-version:
    runs-on: macos-latest
    steps:
      - name: Check and echo python version
        run: echo "python --version"
